### ISSUE TITLE
The system is running in low-graphics mode

### ISSUE THREAD

**Issue by fhunleth** [codestarterorg/ubuntu-chromebook-installer#18]
We had a working Acer C720 with an earlier version of the ubuntu-chromebook-installer working. To refresh it for another student, we reinstalled using the latest installer. The installation worked fine and we've done this with other Chromebooks. However, this time after the language, keyboard, wifi, and username are entered in, the Chromebook displays, "The system is running in low-graphics mode". Additionally, the touchpad doesn't work in this mode. Attaching an external keyboard and mouse, lets you operate the "low-graphics mode" screens, but I can't find an error message for what went wrong. I assumed that I'd seen an error in the Xorg logs, but did not. I've tried wiping the Ubuntu partition and reinstalling but have had no success. 

Any ideas?

**Comment by PlusM** [comment]
This solution was for 12.04, but worked for me a few weeks ago when upgrading the SSD on my C720 and encountering the same issue with the installer for 14.04.

#37 in this thread: http://ubuntuforums.org/showthread.php?t=1968492&page=4

Detail:
After upgrade had "The system is running in low graphics mode"
click ctrl alt F2
sudo apt-get purge nvidia*
sudo apt-get install nvidia-current
These commands gave wallpaper only
sudo dpkg-reconfigure lightdm (to make sure lightdm is used)
then reboot

**Comment by mojombo** [comment]
I've seen this a few times on new machines we've set up. I'm not sure what the exact problem is, but here's how w fix it:

1. Boot up until you see the low graphics mode screen.
2. Hit CTRL-ALT-F2 (F2 is the left arrow on the top row of keys).
3. Login (if you can't login because no user, or you don't know the user, you can use the latest installer and pre-select a username with the following install command: `sudo bash main.sh -u USERNAME`. The password will be `codestarter`.
4. Connect to wifi with `nmcli d wifi connect SSID password PASSWORD iface wlan0` (replace capitalized words with actual SSID and password).
5. run `sudo apt-get update`.
6. run `sudo apt-get upgrade`.

That fixes it for us!

**Comment by fhunleth** [comment]
Thanks. That worked!

**Comment by Ichigo1174** [comment]
Hi i'm having this same problem. when I hit CTRL-ALT-F2 it takes me here.
![20150606_210156](https://cloud.githubusercontent.com/assets/10361815/8022273/1f020b3c-0c95-11e5-8346-04a86eebfcb8.jpg)
i don't have a username or login and I never have so i tired the command in various different ways. but every time I used codestarter it always said "login incorrect"
Am I typing it wrong?

**Comment by mojombo** [comment]
@Ichigo1174 You probably don't have an account you can use to login yet, so you'll need to re-run the installer (make sure you have the latest one), and use this command when you do:

```
sudo bash main.sh -u USERNAME -n
```

Replace USERNAME with your desired username. Your password will be `codestarter`. If you install this way, then you'll be able to login with those credentials.

**Comment by Ichigo1174** [comment]
I'm not sure if I have the latest one. I downloaded and was following this:
https://github.com/codestarterorg/ubuntu-chromebook-installer
so when I should open back up the developer mode and be able to restart it or do I have to like completely start fresh with a recovery image? I'm new to a good bit of this stuff.

**Comment by Ichigo1174** [comment]
I started over and when it came to login I typed
sudo bash main.sh -u Ichigo1174 -n
being that is what I wanted codestarter and it is still telling me login is incorrect. Is there any way I could use a login to fix this issue and then make my own account?

**Comment by ford442** [comment]
I managed to FIX this 100% !!!!!!!!!!!!!!!!!
I was rebooting and rebooting and changing gdm to lightdm and back when I saw in the error messages something like non-recognized screen 0 entry in /etc/X11/xorg.conf
I went to there and it said

Screen 0 "nvidia"
Inactive "intel" 

I simply corrected those obvious entries - my graphics are Intel integrated right now. I had removed the nvidia Geforce. I deleted Inactive "Intel" and changed Screen 0 to "Intel." This is apparently where that changeover does not get reflected and we are left with the endless loop of "This system is running in low-graphics mode."
One reboot and I had desktop, but no launcher - rebooted again and Ubuntu was back to booting fully!
It has been since 2013 that I've been working on a solution to that short of reinstalling and there it is finally. I see one guy who reports that afterward some Ubuntu desktop 3d features are missing until he ran "sudo update-alternatives --remove-all x86_64-linux-gnu-gl-conf" and "sudo update-alternatives --remove-all i386-linux-gnu-gl_conf" then "sudo update-alternatives --remove-all gl_conf" - removed his /X11/xorg.conf and removed 'nogpumanager' from /etc/default/grub - then he could switch from 'XRender' to OpenGL 3.1' in compositing display settings to regain the lost desktop effects.

**Comment by umitkilic** [comment]
@Ichigo1174  it is your fault. first of all, you must write your username, press enter and write your password. After that you should write the command. Example: 
localhost login: username
Password: yourpassword
As simple as that :)

**Comment by umitkilic** [comment]
By the way, none of these solutons didn't work to me. I am still looking for the solution.

**Comment by ghost** [comment]
Thanks for the fix. mojombo's solution worked for me.

**Comment by ghost** [comment]
Hey people none of these solution work to me pls tell me I faced this problem after I installed KDE

**Comment by wqw547243068** [comment]
@mojombo I am sorry, your steps didn't work for me. Nothing came out when executing the command "CTRL-ALT-F2", and I don't know why ...
